repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^home/dot_config/Code/User/settings\.json$ # JSONC (contains comments)
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.1
    hooks:
      - id: markdownlint-cli2
        args: ["--fix"]

  - repo: local
    hooks:
      - id: shellcheck
        name: Shellcheck
        entry: just lint
        language: system
        files: ^scripts/.*\.sh$
        pass_filenames: false
