# Taps
tap "microsoft/apm", trusted: true
tap "mutagen-io/mutagen", trusted: true

# Dev tools
brew "actionlint"
brew "aws-vault"
brew "awscli"
brew "bats-core"
brew "ca-certificates"
brew "gh"
brew "jq"
brew "just"
brew "librsvg" # for `rsvg-convert`
brew "microsoft/apm/apm"
brew "mkcert"
brew "pre-commit"
brew "shellcheck"

# Container and sync
brew "colima"
brew "docker"
brew "mutagen-io/mutagen/mutagen"
brew "mutagen-io/mutagen/mutagen-compose"

# Language and runtimes
brew "bash"
brew "go"
brew "gradle"
brew "openjdk@21"
brew "php"
brew "rbenv"
brew "ruby-build"

# Utilities
brew "ffmpeg"
brew "nkf"
